import { supabase } from './supabase.js';

/**
 * The owner's side of the database.
 *
 * Nothing here is privileged by being in this file. Every call goes out with
 * the signed-in person's own token, and the database decides: the policies
 * behind these tables only admit someone whose id is in the admins table. A
 * parent who opened this page, or who called these functions from a console,
 * would get empty results and refused writes.
 *
 * Which is the point. The admin screen is a convenience built on top of the
 * rules, not the thing enforcing them.
 */

/** Every family, newest first, with their children attached. */
export async function listFamilies() {
  const { data, error } = await supabase
    .from('families')
    .select('*, children(*)')
    .order('created_at', { ascending: false });

  if (error) throw error;

  for (const family of data ?? []) {
    family.children?.sort((a, b) => a.sort_order - b.sort_order);
  }
  return data ?? [];
}

export async function setStatus(familyId, status, reviewNote = null) {
  const { error } = await supabase
    .from('families')
    .update({ status, review_note: reviewNote })
    .eq('id', familyId);

  if (error) throw error;
}

export async function setMinuteLimit(familyId, minutes) {
  const { error } = await supabase
    .from('families')
    .update({ monthly_minute_limit: minutes })
    .eq('id', familyId);

  if (error) throw error;
}

/**
 * Creates an invitation and returns the code.
 *
 * The code is generated by the database, not here, so it comes from
 * pgcrypto's random bytes rather than anything a browser offers.
 */
export async function createInvite(label) {
  const { data: code, error: codeError } = await supabase.rpc('generate_invite_code');
  if (codeError) throw codeError;

  const { data, error } = await supabase
    .from('invites')
    .insert({ code, label: label?.trim() || null })
    .select()
    .single();

  if (error) throw error;
  return data;
}

export async function listInvites() {
  const { data, error } = await supabase
    .from('invites')
    .select('*')
    .order('created_at', { ascending: false });

  if (error) throw error;
  return data ?? [];
}

export async function deleteInvite(code) {
  const { error } = await supabase.from('invites').delete().eq('code', code);
  if (error) throw error;
}

/** The link to send a family. */
export function inviteLink(code) {
  return `${location.origin}/join.html?code=${encodeURIComponent(code)}`;
}

/* --- practice notes ------------------------------------------------------ */

/**
 * The per-family practical guidance, keyed by family id.
 *
 * Admin-only at the database level: a parent cannot read this table at all.
 * It is a professional's read on their child and belongs with the rest of the
 * prompt they never see.
 */
export async function loadPracticeNotes() {
  const { data, error } = await supabase
    .from('practice_notes')
    .select('family_id, notes, source, updated_at');

  if (error) throw error;
  return new Map((data ?? []).map((row) => [row.family_id, row]));
}

export async function savePracticeNotes(familyId, notes, source = 'manual') {
  const trimmed = notes.trim();

  if (!trimmed) {
    const { error } = await supabase.from('practice_notes').delete().eq('family_id', familyId);
    if (error) throw error;
    return;
  }

  const { error } = await supabase
    .from('practice_notes')
    .upsert({ family_id: familyId, notes: trimmed, source }, { onConflict: 'family_id' });

  if (error) throw error;
}
